import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)

"""
Applies transformers to columns of an array or pandas DataFrame.
This estimator allows different columns or column subsets of the 
input to be transformed separately and the features generated by 
each transformer will be concatenated to form a single feature space. 
This is useful for heterogeneous or columnar data, to combine several 
feature extraction mechanisms or transformations into a single transformer.

"""
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)
